name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - stagging

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          echo "No tests implemented yet, skipping..."
          exit 0
